# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menunew.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pendaftaran2 import Pendaftaran
from percobaanis import InputSeleksi
from inputsoal import InputSoal
from kuis import QuizApp
from hasilseleksi import HasilSeleksi
from gameedu import Ui_GameEdukatif


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 721)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.asset2 = QtWidgets.QLabel(self.centralwidget)
        self.asset2.setGeometry(QtCore.QRect(100, 70, 771, 601))
        self.asset2.setStyleSheet("image: url(D:/PBO/qt/main.png);")
        self.asset2.setText("")
        self.asset2.setObjectName("asset2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-410, -450, 1871, 1641))
        self.label.setStyleSheet(
            "image: url(D:/PBO/qt/bg.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 200, 541, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Pendaftaran = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Pendaftaran.setObjectName("Pendaftaran")
        self.verticalLayout.addWidget(self.Pendaftaran)
        self.InputSeleksi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.InputSeleksi.setObjectName("InputSeleksi")
        self.verticalLayout.addWidget(self.InputSeleksi)
        self.InputSoal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.InputSoal.setObjectName("InputSoal")
        self.verticalLayout.addWidget(self.InputSoal)
        self.Pretest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Pretest.setObjectName("Pretest")
        self.verticalLayout.addWidget(self.Pretest)
        self.hasilseleksi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.hasilseleksi.setObjectName("hasilseleksi")
        self.verticalLayout.addWidget(self.hasilseleksi)
        self.gameedukatif = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.gameedukatif.setObjectName("gameedukatif")
        self.verticalLayout.addWidget(self.gameedukatif)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 70, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.asset2.raise_()
        self.verticalLayoutWidget.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu PPDB"))
        self.Pendaftaran.setText(_translate("MainWindow", "Pendaftaran"))
        self.InputSeleksi.setText(_translate("MainWindow", "Input Seleksi"))
        self.InputSoal.setText(_translate("MainWindow", "Input Soal"))
        self.Pretest.setText(_translate("MainWindow", "Pretest"))
        self.hasilseleksi.setText(_translate("MainWindow", "Hasil Seleksi"))
        self.gameedukatif.setText(_translate("MainWindow", "Game Edukatif"))
        self.label_2.setText(_translate("MainWindow", "PPDB"))

        def openPendaftaranWindow():
            self.pendaftaran_dialog = QtWidgets.QMainWindow()
            self.pendaftaran_ui = Pendaftaran()
            self.pendaftaran_ui.setupUi(self.pendaftaran_dialog)
            self.pendaftaran_dialog.show()

        self.Pendaftaran.clicked.connect(openPendaftaranWindow)

        def inputSeleksiWindow():
            self.inputSeleksi_dialog = QtWidgets.QMainWindow()
            self.inputSeleksi_ui = InputSeleksi()
            self.inputSeleksi_ui.show()

        self.InputSeleksi.clicked.connect(inputSeleksiWindow)

        def InputSoalWindow():
            self.inputSoal_dialog = QtWidgets.QMainWindow()
            self.inputSoal_ui = InputSoal()
            self.inputSoal_ui.setupUi(self.inputSoal_dialog)
            self.inputSoal_dialog.show()

        self.InputSoal.clicked.connect(InputSoalWindow)

        def Kuis():
            self.kuis_ui = QuizApp()
            self.kuis_ui.show()

        self.Pretest.clicked.connect(Kuis)

        def Hasilseleksi():
            self.hasil_dialog = QtWidgets.QMainWindow()
            self.hasil_ui = HasilSeleksi()
            self.hasil_ui.setupUi(self.hasil_dialog)
            self.hasil_dialog.show()

        self.hasilseleksi.clicked.connect(Hasilseleksi)

        def gameedukatif():
            self.hasil_dialog = QtWidgets.QMainWindow()
            self.hasil_ui = Ui_GameEdukatif()
            self.hasil_ui.setupUi(self.hasil_dialog)
            self.hasil_dialog.show()

        self.gameedukatif.clicked.connect(gameedukatif)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
